#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jan 31 20:01:13 CET 2024
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_core_mem_behav -key {Behavioral:memory_test:Functional:tb_core_mem} -tclbatch tb_core_mem.tcl -view /home/pawel24pl/Programy/Vivado/Neurons2/Neurons2/tb_core_learning_behav.wcfg -log simulate.log"
xsim tb_core_mem_behav -key {Behavioral:memory_test:Functional:tb_core_mem} -tclbatch tb_core_mem.tcl -view /home/pawel24pl/Programy/Vivado/Neurons2/Neurons2/tb_core_learning_behav.wcfg -log simulate.log

